/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
*/

#include "global_var.h"

uint32_t sum_volt = 0;
int avg_y = 0;
int trigger_point;
int prev[280] = {0};
int curr_y;
int prev_y;

int main(void) {
    RCC_Init();
    DMA_Init();
    SPI_Init();
    GPIO_Init();
    ILI9341_Init();
    ADC_Init();
    TIM2_Init();
    PWM_Init();

    ILI9341_Set_Address(0, 0, 319, 239);
    for(int i = 0; i < (240 * 320); i++) {
        Send_Data(0x00); Send_Data(0x00);
    }

    ILI9341_Borders();

    while(1) {
    	if(data_ready_flag){

    		data_ready_flag = 0;
    		trigger_point = Find_Trigger(safe_buffer, 500);

    		if(trigger_point == -1)
    		{
    			trigger_point = 0;
    		}
    		for(int i = 0; i < 280; i++){
    			curr_y = (safe_buffer[trigger_point + i] * 198) >> 12;
    			curr_y += 22;

    			if(prev[i] != curr_y){
					ILI9341_Set_Address(i + 20, prev[i], i + 20, prev[i]);
					Send_Data(0x00); Send_Data(0x00); // clearing previous graph
					ILI9341_Set_Address(i + 20, curr_y, i + 20, curr_y);
					Send_Data(0xFF); Send_Data(0xFF); // writing new graph
					prev[i] = curr_y;
    			}
    		}
    	}
    }
}
